enum types {
    SET_CATEGORY = 'SET_CATEGORY',
    SET_FACETS = 'SET_FACETS',
    SET_PAGINATION = 'SET_PAGINATION',
    SET_PAGINATION_NUMBER = 'SET_PAGINATION_NUMBER',
    SET_PRODUCT_VIEW = 'SET_PRODUCT_VIEW',
    SET_PRODUCTS = 'SET_PRODUCTS',
    SET_SELECTED_FILTERS = 'SET_SELECTED_FILTERS',
    SET_SORT_TYPE = 'SET_SORT_TYPE'
};

export default types;
