enum types {
    SET_CATEGORY = 'SET_CATEGORY',
    SET_PAGINATION_INFO = 'SET_PAGINATION_INFO',
    SET_PAGINATION_NUMBER = 'SET_PAGINATION_NUMBER',
    SET_PRODUCTS = 'SET_PRODUCTS',
    SET_SORT_BY = 'SET_SORT_BY'
};

export default types;
